config/routes.rb
Rails.application.routes.draw do
 
  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
  get 'notifications', to: 'notifications#index'
  get 'profiles/show'
  
  root to: 'posts#index'

  devise_for :users, :controllers => {registrations: 'registrations'}
  
	resources :posts do
		resources :comments
		member	do
			get	'like' => "posts#like"
			get	'unlike' => "posts#unlike"
		end	
	end
	
	resources :notifications

	mount ActionCable.server => '/cable'

	# Existing route id to user_name
	get	':user_name', to: 'profiles#show', as: :profile
	# New route edit_profile
	get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
	#New routes update_profile
	patch ':user_name/edit', to: 'profiles#update', as: :update_profile
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :notified_by, class_name: 'User'
  belongs_to :post
  belongs_to :user

  #validates :user_id, :notified_by_id, :post_id, :identifier, :notice_type, presence: true
   after_create_commit { NotificationBroadcastJob.perform_later(Notification.count,self)}
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  
  def index
  	@notifications = current_user.notifications.reverse	
  end

  def link_through
  @notification = Notification.find(params[:id])
  @notification.update read: true
  redirect_to post_path @notification.post
  end

end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_counter.html.erb
<span  id="notification-counter"><%= counter %></span>

app/views/notifications/_notification.html.erb
<li>
  <%= link_to "#{notification.notified_by.user_name} has #{notification.notice_type}ed on your post", link_through_path(notification) %>
  <%= time_ago_in_words notification.created_at %>
</li>

app/views/notifications/_notification_dropdown.html.erb
<div class="dropdown notification-dropdown">
      <button class="btn btn-default dropdown-toggle"
      type = 'button'
      id = 'dropdownMenu1'
      data-toggle = 'dropdown'
      aria-haspopup = 'true' 
      aria-expanded = 'true'  >
        <%= render 'notifications/counter', counter: current_user.notifications.count %>
        <span class="glyphicon glyphicon-flag"></span>
      </button>
      <ul class="dropdown-menu" aria-labelledby = 'dropdownMenu1'>
        <li class="dropdown-header text-center">Notifications</li>
      	<li id="notificationList" ><%= render current_user.notifications.order('created_at DESC').last(5) %></li>
      	<li class="divider" role="separator">
	  		<li class="text-center">
	    		<%= link_to 'View All', notifications_path %>
	  		</li>
		    </li>
		    </li>
      </ul>
    </div>

app/views/notifications/index.html.erb
 
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <ul class="notification-index-list" id="notificationList">
  			<%= render @notifications %>	
      </ul>
    </div>
  </div>
</div>

app/views/notifications/link_through.html.erb
<h1>Notifications#link_through</h1>
<p>Find me in app/views/notifications/link_through.html.erb</p>